-- 코드를 입력하세요
SELECT A.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR   A
  LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY   B
         ON A.CAR_ID = B.CAR_ID
 WHERE A.CAR_TYPE = '세단'
   AND B.START_DATE > TO_DATE('20221001', 'YYYY-MM-DD')
 GROUP BY A.CAR_ID
 ORDER BY A.CAR_ID DESC